--
-- PostgreSQL database dump
--

-- Dumped from database version 8.4.2
-- Dumped by pg_dump version 9.3.1
-- Started on 2017-07-01 18:15:57

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = off;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET escape_string_warning = off;

SET search_path = public, pg_catalog;

SET default_tablespace = '';

SET default_with_oids = false;

--
-- TOC entry 143 (class 1259 OID 28692)
-- Name: news; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE news (
    nid integer NOT NULL,
    chid integer,
    title text,
    link text,
    description text,
    "pubDate" timestamp with time zone,
    likes integer
);


ALTER TABLE public.news OWNER TO postgres;

--
-- TOC entry 1796 (class 0 OID 0)
-- Dependencies: 143
-- Name: COLUMN news.nid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN news.nid IS 'news id';


--
-- TOC entry 1797 (class 0 OID 0)
-- Dependencies: 143
-- Name: COLUMN news.chid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN news.chid IS 'channel id (from table rss_channels)';


--
-- TOC entry 142 (class 1259 OID 28690)
-- Name: news_nid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE news_nid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.news_nid_seq OWNER TO postgres;

--
-- TOC entry 1798 (class 0 OID 0)
-- Dependencies: 142
-- Name: news_nid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE news_nid_seq OWNED BY news.nid;


--
-- TOC entry 140 (class 1259 OID 28617)
-- Name: rss_channels; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE rss_channels (
    name text,
    url text,
    link text,
    chid integer NOT NULL
);


ALTER TABLE public.rss_channels OWNER TO postgres;

--
-- TOC entry 141 (class 1259 OID 28633)
-- Name: rss_channels_chid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE rss_channels_chid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.rss_channels_chid_seq OWNER TO postgres;

--
-- TOC entry 1799 (class 0 OID 0)
-- Dependencies: 141
-- Name: rss_channels_chid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE rss_channels_chid_seq OWNED BY rss_channels.chid;


--
-- TOC entry 1694 (class 2604 OID 28695)
-- Name: nid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY news ALTER COLUMN nid SET DEFAULT nextval('news_nid_seq'::regclass);


--
-- TOC entry 1693 (class 2604 OID 28635)
-- Name: chid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY rss_channels ALTER COLUMN chid SET DEFAULT nextval('rss_channels_chid_seq'::regclass);


--
-- TOC entry 1788 (class 0 OID 28692)
-- Dependencies: 143
-- Data for Name: news; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (15, 2, 'Виталий Мутко: Финал Кубка конфедераций посетят 53 тысячи зрителей', 'https://news.yandex.ru/yandsearch?cl4url=rg.ru%2F2017%2F07%2F01%2Fvitalij-mutko-final-kubka-konfederacij-posetiat-53-tysiachi-zritelej.html', 'В Санкт-Петербурге 2 июля состоится финал Кубка конфедераций, который посетят не менее 53 тысяч человек. Именно столько билетов уже продано, сообщил &quot;Интерфаксу&quot; вице-премьер РФ, президент Российского футбольного союза Виталий Мутко.', '2017-07-01 11:03:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (14, 2, 'Арбитр Мажич обслужит финальный матч Кубка конфедераций', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F613360', 'Сербский арбитр Милорад Мажич обслужит финал Кубка конфедераций, в котором будут играть соборная Германия и сборная Чили. Об этом пишет «Газета.ру» со ссылкой на «Р-Спорт».', '2017-07-01 10:58:05+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (129, 4, 'Названы восемь основных причин утренней головной боли', 'https://news.yandex.ru/yandsearch?cl4url=www.tatar-inform.ru%2Fnews%2F2017%2F07%2F01%2F560811%2F', 'Доктор Сальваторе Наполи из Центра неврологии Новой Англии назвал восемь основных причин утренней головной боли, пишет kp.ru. Среди них на первом месте идут недосып и долгий сон. Отмечается, что человеку в среднем требуется семь или восемь часов сна в сутки.', '2017-07-01 17:48:52+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (130, 4, 'За последние два месяца около 200 детей в Челнах покусали клещи', 'https://news.yandex.ru/yandsearch?cl4url=www.tatar-inform.ru%2Fnews%2F2017%2F07%2F01%2F560796%2F', 'За последние два месяца за помощью в травмпункт Камского детского медицинского центра после укусов клещей обратились около 200 маленьких пациентов. Об этом сообщает пресс-служба КДМЦ Набережных Челнов.', '2017-07-01 15:33:54+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (11, 2, 'Президент ФИФА назвал Кубок конфедераций большим успехом', 'https://news.yandex.ru/yandsearch?cl4url=www.ntv.ru%2Fnovosti%2F1830221%2F', 'Глава ФИФА Джанни Инфантино поблагодарил оргкомитет Кубка конфедераций, РФС и всех россиян и заявил, что Кубок конфедераций стал большим успехом со многих точек зрения. Инфантино рассказал, что Кубок конфедераций проходит без негативных явлений; опасения, что в России будут проблемы, не оправдались.', '2017-07-01 12:44:00+04', 10);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (133, 4, 'В Приморье откроется еще один перинатальный центр', 'https://news.yandex.ru/yandsearch?cl4url=www.vladtime.ru%2Fzdorov%2F585699', 'По инициативе губернатора Приморского края в перинатальный краевой центр закупят оборудование для особых операций и транспортировки новорожденных, а также постоят новый. Деньги на это будут выделены из бюджета Приморского края.', '2017-07-01 16:12:15+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (131, 4, 'Молодоженам Благовещенска выдают сертификаты на обследования и ЭКО', 'https://news.yandex.ru/yandsearch?cl4url=www.amur.info%2Fnews%2F2017%2F06%2F30%2F126615', 'Молодожёны получили возможность пройти бесплатное обследование. Парам, зарегистрировавшим свой брак, теперь выдают сертификаты здоровья.', '2017-06-30 14:44:08+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (132, 4, 'В России выросла смертность от грязной воды', 'https://news.yandex.ru/yandsearch?cl4url=pravdaurfo.ru%2Fnews%2F154401-v-rossii-vyrosla-smertnost-ot-gryaznoy-vody', 'Роспотребнадзор РФ сообщил о росте смертности из-за грязной питьевой воды. В 2016 году по сравнению с предыдущим годом цифра увеличилась почти втрое: с 6 до 19 тыс. случаев.', '2017-06-30 09:28:39+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (134, 4, 'В Воронежской области клещи стали агрессивнее', 'https://news.yandex.ru/yandsearch?cl4url=vestivrn.ru%2Flenta%2Fv-voronezhskoy-oblasti-kleschi-stali-agressivnee_2017-6-28_10-5', 'Медики советуют пользоваться репеллентами, выезжая на природу. Число укушенных клещами в Воронежской области за 10 дней увеличилось на 340 человек. Всего к медикам с начала сезона обратилось около полутора тысяч пострадавших.', '2017-06-28 11:05:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (135, 4, 'Об изменениях в порядке государственной регистрации генно-инженерно-модифицированных организмов и продукции, полученной с их применением', 'https://news.yandex.ru/yandsearch?cl4url=glasnarod.ru%2Fvlast%2F99572-ob-izmeneniyax-v-poryadke-gosudarstvennoj-registraczii-genno-inzhenerno-modificzirovannyx-organizmov-i-produkczii-poluchennoj-s-ix-primeneniem', 'В Правила государственной регистрации генно-инженерно-модифицированных организмов, предназначенных для выпуска в окружающую среду, и продукции, полученной с применением таких организмов или содержащей такие организмы, внесены изменения, которыми, в частности, полномочия по мониторингу и контролю в области генно-инженерной деятельности закреплены за Роспотребнадзором и Россельхознадзором.', '2017-07-01 11:57:46+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (140, 5, 'Американский авианосец George H. W. Bush прибыл в израильский порт', 'https://news.yandex.ru/yandsearch?cl4url=www.gazeta.ru%2Farmy%2Fnews%2F10249757.shtml', 'Авианосец ВМС США George H. W. Bush прибыл с визитом в израильский порт Хайфа. Об этом сообщает Jerusalem Post. Как отмечает издание, авианосец бросил якорь рядом с портом, поскольку из-за своих размеров не может остановиться непосредственно в нем.', '2017-07-01 17:35:30+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (141, 5, 'Европа простилась в Страсбурге с «канцлером единства» Гельмутом Колем', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fmezhdunarodnaya-panorama%2F4380615', 'Европа простилась с бывшим канцлером ФРГ, первым руководителем объединенной Германии Гельмутом Колем (1930-2017). Официальная общеевропейская траурная церемония состоялась в субботу в здании Европейского парламента (ЕП) в Страсбурге.', '2017-07-01 16:53:48+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (142, 5, 'СМИ сообщили о подтверждении гибели аль-Багдади его помощником', 'https://news.yandex.ru/yandsearch?cl4url=www.interfax.ru%2Fworld%2F568775', 'Иранское агентство FARS со ссылкой на СМИ сообщило, что близкий друг и помощник лидера &quot;Исламского государства&quot; (запрещено в РФ) косвенно подтвердил гибель Абу Бакра аль-Багдади.', '2017-07-01 14:13:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (17, 2, 'Диего Марадона заявил о готовности возглавить сборную России', 'https://news.yandex.ru/yandsearch?cl4url=rg.ru%2F2017%2F06%2F30%2Freg-cfo%2Fdiego-maradona-zaiavil-o-gotovnosti-vozglavit-sbornuiu-rossii.html', 'Пока же Марадона проводит время в столице. И в одном из первых заявлений, которое он сделал в интервью &quot;Советскому Спорту&quot;, великий аргентинец признался, что готов стать новым главным тренером сборной России.', '2017-06-30 20:53:00+04', 3);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (136, 4, 'Медики не советуют медлить при инсульте', 'https://news.yandex.ru/yandsearch?cl4url=versiya.info%2Fzdorovye%2F20211', 'По мнению специалистов огромная ответственности в случаях инсульта ложится на окружающих и в этом случае беспечность может дорого обойтись. Поэтому при инсульте медлить ни в коем случае нельзя. Со слов медиков острое нарушение кровообращения в мозгу может пройти абсолютно неожиданно.', '2017-06-30 21:30:19+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (137, 4, 'Тюменские врачи налаживают связи с японскими коллегами', 'https://news.yandex.ru/yandsearch?cl4url=tumentoday.ru%2F2017%2F07%2F01%2Ftyumenskie-vrachi-nalazhivayut-svyazi-s-yaponskimi-kollegami%2F', 'Как сообщили в пресс-службе регионального департамента инвестиционной политики и государственной поддержки предпринимательства, планируется, что в рамках своего визита доктор Акира Сакаи посетит тюменский Медицинский город и проведет переговоры об участии японской стороны в строительстве и оснащении будущего онкологического центра областного медицинского кластера.', '2017-07-01 14:02:49+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (138, 4, 'На Байконур обрушилась чума, жителей предупредили об угрозе', 'https://news.yandex.ru/yandsearch?cl4url=ok-inform.ru%2Fobshchestvo%2Fproisshestviya%2F95846-na-bajkonur-obrushilas-chuma-zhitelej-predupredili-ob-ugroze.html', 'Как сообщает ИА «Народные новости», есть угроза заражения людей. Администрация Байконура, расположенного на юге Казахстана, призвала граждан к бдительности и осторожности при выезде за пределы города. В окрестностях космического комплекса зафиксирован активный природный очаг чумы.', '2017-06-30 12:04:38+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (139, 4, 'Статистики рассказали, от чего чаще всего умирают омичи', 'https://news.yandex.ru/yandsearch?cl4url=newsomsk.ru%2Fnews%2F59325-statistiki_rasskazali_ot_chego_chachshe_vsego_umir%2F', 'Причина 80% всех смертей в Омской области приходится всего на четыре класса болезней. По данным Омскстата, в 2016 году в регионе умерли 26 152 человека — на 1,2% меньше, чем годом ранее.', '2017-07-01 12:46:39+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (143, 5, 'Дейр-эз-Зору в Сирии грозит гумкатастрофа из-за дамбы на Евфрате', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F613444', 'Гуманитарная катастрофа может разразиться из-за дамбы на Евфрате, которую строят боевики ИГ («Исламское государство», запрещено в РФ). Об этом заявили СМИ источники в дипломатических кругах.', '2017-07-01 16:02:48+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (41, 3, 'Налог на имущество воронежцев рассчитывается по кадастровой стоимости', 'https://news.yandex.ru/yandsearch?cl4url=www.vrn.kp.ru%2Fdaily%2F26698%2F3723077%2F', 'Налог на имущество физических лиц уплачивают собственники квартир, жилых домов и других помещений. С 1 января 2016 года его размер определяется, исходя из кадастровой стоимости объекта. Это стоимость недвижимости, приближенная к рыночной.', '2017-06-30 14:20:00+04', 10);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (144, 5, 'Кэрри Лам официально вступила в должность главы Гонконга', 'https://news.yandex.ru/yandsearch?cl4url=rg.ru%2F2017%2F07%2F01%2Fkerri-lam-oficialno-vstupila-v-dolzhnost-glavy-gonkonga.html', 'В мероприятии, которое прошло в субботу, принял участие председатель КНР Си Цзиньпин. Он прибыл на торжества по случаю 20-й годовщины перехода бывшего британского анклава под китайскую юрисдикцию. Лам стала первой женщиной на высшем должностном посту в Гонконге и будет занимать его пять лет.', '2017-07-01 08:36:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (145, 5, 'СБУ обвиняет РФ в причастности к вирусу Petya.A', 'https://news.yandex.ru/yandsearch?cl4url=www.gazeta.ru%2Fpolitics%2F2017%2F07%2F01_a_10757519.shtml', 'В Совфеде назвали эти обвинения надуманными для получения финансовой помощи от западных стран. Служба безопасности Украины (СБУ) заподозрила российские спецслужбы в причастности к атаке вируса Petya.A на IT-системы компаний в нескольких странах. Об этом в субботу сообщил пресс-центр СБУ.', '2017-07-01 17:48:24+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (146, 5, 'В Волгоградской области по тревоге подняли более 500 военных', 'https://news.yandex.ru/yandsearch?cl4url=www.volgograd.kp.ru%2Fonline%2Fnews%2F2793442%2F', 'На Полигоне Прудбой в Волгоградской области учебная тревога подняла более 500 военнослужащих. Как сообщили «КП-Волгоград» в пресс-службе ЮВО, командующий 8-ой общевойсковой армией генерал-лейтенант Сергей Кузовелев решил проверить боевую готовность мотострелкового соединения ЮВО.', '2017-07-01 11:01:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (147, 5, 'New York Post опубликовала статью о Трампе из трех слов', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fmezhdunarodnaya-panorama%2F4380139', 'Американская газета New York Post опубликовала статью, посвященную президенту США Дональду Трампу, которая состоит всего из трех слов. Соответствующий материал появился в печатном номере издания в пятницу.', '2017-07-01 06:40:33+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (148, 5, 'Пентагон отложил на полгода прием трансгендеров в армию', 'https://news.yandex.ru/yandsearch?cl4url=echo.msk.ru%2Fnews%2F2010462-echo.html', 'В прошлом году тогдашний министр обороны Эштон Картер объявил об отмене запрета с 1 июля. Теперь запрет планируется снять 1 января.', '2017-07-01 11:30:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (149, 5, 'Журналисты попытались уронить на Трампа лампу', 'https://news.yandex.ru/yandsearch?cl4url=regnum.ru%2Fnews%2Fpolit%2F2295276.html', 'Встреча лидеров США и Южной Кореи проходила в Овальном кабинете Белого дома. Во время протокольной съёмки журналисты дважды едва не опрокинули стоящую на журнальном столике возле американского лидера лампу. Этот курьёзный инцидент вызвал заметное раздражение у Трампа.', '2017-07-01 09:00:46+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (150, 5, 'Генпрокурор Украины сообщил о новых подозрениях против Януковича', 'https://news.yandex.ru/yandsearch?cl4url=www.ntv.ru%2Fnovosti%2F1830059%2F', 'Как написал в своем Facebook генпрокурор Юрий Луценко, речь идет о незаконном препятствовании организации и проведению собраний, митингов, походов и демонстраций, организации превышения работниками правоохранительных органов власти и служебных полномочий, умышленном убийстве двух и более лиц, причинении умышленного тяжкого телесного повреждения, а также организации теракта.', '2017-07-01 05:18:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (151, 6, 'В ночном клубе Литл-Рока произошла стрельба: 17 человек пострадали', 'https://news.yandex.ru/yandsearch?cl4url=rg.ru%2F2017%2F07%2F01%2Fv-nochnom-klube-litl-roka-proizoshla-strelba-17-chelovek-postradali.html', 'В одном из ночных клубов американского штата Арканзас произошла стрельба, в результате которой пострадали 17 человек. Об этом сообщает РИА Новости со ссылкой на Fox News. Один раненый находится в критическом состоянии.', '2017-07-01 16:13:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (152, 6, 'В Раде предложили альтернативу визовому режиму с Россией', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497647692.html', 'Депутат Верховной рады Антон Геращенко считает, что вместо визового режима с Россией нужно ввести регистрацию приезжих россиян на &quot;специальных сайтах&quot;. Об этом он заявил в эфире канала &quot;112 Украина&quot;.', '2017-07-01 10:24:41+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (153, 6, 'В Токио вступил в силу запрет на свидания за деньги для школьниц', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fobschestvo%2F4380109', 'Запрет на работу в сфере свиданий за деньги вступил в субботу в Токио для школьниц моложе 18 лет. Соответствующее постановление было принято в пятницу государственным законодательным собранием японской столицы.', '2017-07-01 04:33:36+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (9, 6, '«АвтоВАЗ» рассекретил дизайн Lada Vesta SW и Vesta SW Cross', 'https://news.yandex.ru/yandsearch?cl4url=gazeta.a42.ru%2Flenta%2Fnews%2Favtovaz-rassekretil-dizajn-lada-vesta-sw-i-vesta-sw-cross', 'Отечественный производитель представил серийную версию универсала Lada Vesta SW и его вседорожную модификацию Vesta SW Cross. Автомобили отличаются обновлённым дизайном, увеличенными размерами, более серьёзным клиренсом.', '2017-06-28 09:35:59+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (154, 6, 'МЧС: в Москве вновь ожидается гроза с сильным ветром', 'https://news.yandex.ru/yandsearch?cl4url=tourism.interfax.ru%2Fru%2Fnews%2Farticles%2F42038', 'Ранее ливень, который обрушился на Москву 30 июня, принес в столичный регион 90% месячной нормы осадков. Ливни сопровождались грозами и шквалистым ветром. Из-за непогоды погибли двое и пострадали 16 человек.', '2017-07-01 16:27:12+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (155, 6, 'СБУ обвиняет РФ в причастности к вирусу Petya.A', 'https://news.yandex.ru/yandsearch?cl4url=www.gazeta.ru%2Fpolitics%2F2017%2F07%2F01_a_10757519.shtml', 'В Совфеде назвали эти обвинения надуманными для получения финансовой помощи от западных стран. Служба безопасности Украины (СБУ) заподозрила российские спецслужбы в причастности к атаке вируса Petya.A на IT-системы компаний в нескольких странах. Об этом в субботу сообщил пресс-центр СБУ.', '2017-07-01 17:48:24+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (156, 6, 'Европа простилась в Страсбурге с «канцлером единства» Гельмутом Колем', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fmezhdunarodnaya-panorama%2F4380615', 'Европа простилась с бывшим канцлером ФРГ, первым руководителем объединенной Германии Гельмутом Колем (1930-2017). Официальная общеевропейская траурная церемония состоялась в субботу в здании Европейского парламента (ЕП) в Страсбурге.', '2017-07-01 16:53:48+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (157, 6, 'Число пострадавших в результате непогоды в Москве выросло до 16', 'https://news.yandex.ru/yandsearch?cl4url=www.vedomosti.ru%2Fpolitics%2Fnews%2F2017%2F07%2F01%2F705720-chislo-postradavshih-viroslo', 'По последним данным, в результате непогоды в Москве пострадали 16 человек, сообщает ТАСС со ссылкой на источник в медицинских службах.', '2017-07-01 11:39:16+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (158, 6, 'New York Post опубликовала статью о Трампе из трех слов', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fmezhdunarodnaya-panorama%2F4380139', 'Американская газета New York Post опубликовала статью, посвященную президенту США Дональду Трампу, которая состоит всего из трех слов. Соответствующий материал появился в печатном номере издания в пятницу.', '2017-07-01 06:40:33+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (159, 6, 'Журналисты попытались уронить на Трампа лампу', 'https://news.yandex.ru/yandsearch?cl4url=regnum.ru%2Fnews%2Fpolit%2F2295276.html', 'Встреча лидеров США и Южной Кореи проходила в Овальном кабинете Белого дома. Во время протокольной съёмки журналисты дважды едва не опрокинули стоящую на журнальном столике возле американского лидера лампу. Этот курьёзный инцидент вызвал заметное раздражение у Трампа.', '2017-07-01 09:00:46+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (160, 6, 'В России повысили МРОТ на 300 рублей', 'https://news.yandex.ru/yandsearch?cl4url=www.gazeta.ru%2Fbusiness%2Fnews%2F2017%2F07%2F01%2Fn_10248287.shtml', 'Минимальный размер оплаты труда (МРОТ) в России с 1 июля 2017 года вырастет с 7,5 тыс. до 7,8 тыс. руб. в месяц, передает РИА &quot;Новости&quot;.', '2017-07-01 04:37:17+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (161, 6, 'Генпрокурор Украины сообщил о новых подозрениях против Януковича', 'https://news.yandex.ru/yandsearch?cl4url=www.ntv.ru%2Fnovosti%2F1830059%2F', 'Как написал в своем Facebook генпрокурор Юрий Луценко, речь идет о незаконном препятствовании организации и проведению собраний, митингов, походов и демонстраций, организации превышения работниками правоохранительных органов власти и служебных полномочий, умышленном убийстве двух и более лиц, причинении умышленного тяжкого телесного повреждения, а также организации теракта.', '2017-07-01 05:18:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (162, 6, 'Путин обсудил с Меркель предстоящий саммит G20', 'https://news.yandex.ru/yandsearch?cl4url=www.rbc.ru%2Frbcfreenews%2F5956bc6a9a794752b59f2023', 'Президент Владимир Путин провел телефонные переговоры с канцлером Германии Ангелой Меркель, говорится в сообщении пресс-службы Кремля. основной темой разговора стал предстоящий в июле саммит группы G20. В Кремле уточнили, что разговор состоялся по инициативе Берлина.', '2017-07-01 01:10:23+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (163, 6, 'Потоп века в Москве задержал 450 авиарейсов', 'https://news.yandex.ru/yandsearch?cl4url=mir24.tv%2Fnews%2F16255748', 'В Москве из-за непогоды задержаны 450 авиарейсов, еще 40 отменены. Пассажирам приходится ждать посадки по несколько часов.', '2017-07-01 15:17:24+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (69, 4, 'Руководство Байконура проведет вакцинацию работников от чумы', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F613085', 'Руководству космического комплекса Байконур рекомендовали провести дезинфекцию территории и вакцинировать сотрудников в связи с выявлением чумы у грызунов около одноименного города. Заболеваний среди населения и домашних животных не зарегистрировано.', '2017-06-30 16:34:14+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (170, 2, 'Инфантино поблагодарил Россию за проведение Кубка конфедераций', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fsport%2F4380307', 'Президент Международной федерации футбола (ФИФА) Джанни Инфантино на пресс-конференции в Санкт-Петербурге поблагодарил Россию за успешное проведение Кубка конфедераций 2017 года.', '2017-07-01 12:24:53+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (171, 1, 'Ряд штатов США отказался передать данные о голосовавших на выборах', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F613399', 'Как минимум 24 штата в США отказываются предоставлять регистрационные данные о голосовавших на выборах президента 2016 года.', '2017-07-01 13:41:35+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (81, 5, 'Лавров и Киссинджер обсудили «ненормальные» отношения России и США', 'https://news.yandex.ru/yandsearch?cl4url=www.rbc.ru%2Fpolitics%2F30%2F06%2F2017%2F59560ec59a794776dc10e7a2', 'Министр иностранных дел России Сергей Лавров на «Примаковских чтениях» совместно с бывшим госсекретарем США Генри Киссинджером обсудили внешнюю политику обеих стран. Глава МИД при этом затронул тему будущей встречи президентов Владимира Путина и Дональда Трампа, сообщает корреспондент РБК.', '2017-06-30 12:52:20+04', 10);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (164, 2, 'Капитан сборной Германии: российский народ очень тепло принял нас', 'https://news.yandex.ru/yandsearch?cl4url=russian.rt.com%2Fsport%2Fnews%2F404825-draksler-rossiyane-priyom', 'Капитан и полузащитник сборной Германии по футболу Юлиан Дракслер поделился мнением об уровне организации Кубка конфедераций 2017 года в России.', '2017-07-01 18:05:30+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (165, 2, 'Вслед за Криштиану Роналду сборную Португалии покинул Геррейру', 'https://news.yandex.ru/yandsearch?cl4url=www.sport-express.ru%2Ffootball%2Fconfederations-cup%2Fnews%2Fvsled-za-krishtianu-ronaldu-sbornuyu-portugalii-pokinul-gerreyru-1276463%2F', 'Расположение сборной Португалии помимо нападающего Криштиану Роналду покинул защитник Рафаэл Геррейру, получивший травму во время одного из матчей Кубка конфедераций-2017. Футболист дортмундской &quot;Боруссии&quot; улетел из России вчера утром.', '2017-07-01 12:15:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (166, 2, 'В чемпионате по футболу для дружбы победила оранжевая сборная', 'https://news.yandex.ru/yandsearch?cl4url=www.sport-express.ru%2Ffootball%2Fnews%2Fv-chempionate-po-futbolu-dlya-druzhby-pobedila-oranzhevaya-sbornaya-1276540%2F', 'В субботу в Санкт-Петербурге состоялся первый международный чемпионат по футболу для дружбы. В турнире принимали участие восемь Сборных Дружбы, составленных из юных игроков пятого сезона Детской Международной программы &quot;Футбол для дружбы&quot;.', '2017-07-01 15:48:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (167, 2, 'Сборная Германии обыграла Мексику и вышла в финал Кубка конфедераций', 'https://news.yandex.ru/yandsearch?cl4url=www.gazeta.ru%2Fsport%2F2017%2F06%2F30%2Fa_10756115.shtml', 'Во время второго полуфинала Кубка конфедераций между сборными Германии и Мексики стадион &quot;Фишт&quot; в Сочи посетили 38 тыс. болельщиков. 87% из них были россиянами, большинство отдало свое предпочтение центральноамериканской команде. Кубок конфедераций вступает в свою решающую стадию.', '2017-06-30 20:07:57+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (168, 1, 'Невада начала продажу марихуаны для развлекательных целей', 'https://news.yandex.ru/yandsearch?cl4url=www.rbc.ru%2Frbcfreenews%2F5957aa439a794793fcefa84b', 'Невада стала пятым штатом в США, продающим марихуану для рекреационных целей. Об этом сообщает Associated Press. По данным агентства, жителям штата старше 21 года с удостоврением личности можно приобрести до унции марихуаны (28,3 грамма).', '2017-07-01 18:17:34+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (172, 3, 'Примсоцбанк снизил ставки на отдельные ипотечные программы', 'https://news.yandex.ru/yandsearch?cl4url=www.ludiipoteki.ru%2Fnews%2Findex%2Fthemes%2F271%2Fentry%2Fprimsocbank-snizil-stavki-po-ipoteke-1%2F', 'Ставка на приобретение отдельной комнаты в многоквартирном доме или отдельной доли в квартире составляет 12-12.5 % годовых. Максимальная сумма кредита при этом не может превышать 80% от стоимости.', '2017-06-30 17:25:15+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (175, 6, 'В Киеве прокомментировали арест украинского военного в Италии', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497659080.html', '&quot;Генпрокуратура удивлена арестом в Италии украинского солдата Маркива Виталия, по подозрению в убийстве фоторепортера Андреа Рокелли вблизи города Славянск в мае 2014 года, выдвинутого прокуратурой города Павия&quot;, — написал Енин на своей странице в Facebook.', '2017-07-01 16:34:02+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (173, 4, 'Ученые: Длительное вскармливание молоком портит зубы ребенка', 'https://news.yandex.ru/yandsearch?cl4url=oane.ws%2F2017%2F07%2F01%2Fuchenye-dlitelnoe-vskarmlivanie-molokom-uhudshaet-zuby-rebenka.html', 'Ученые отмечают, что при длительном вскармливании грудью стоматологические проблемы у детей возникают в 2,4 раза чаще, чем у тех малышей, кому давали грудное молоко меньше года или год.', '2017-07-01 16:46:13+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (174, 5, 'Путин обсудил с королем Бахрейна ситуацию вокруг Катара', 'https://news.yandex.ru/yandsearch?cl4url=rg.ru%2F2017%2F07%2F01%2Fputin-obsudil-s-korolem-bahrejna-situaciiu-vokrug-katara.html', 'Президент России провел телефонный разговор с королем Бахрейна. Беседа состоялась по инициативе бахрейнской стороны. Владимир Путин и Хамад Бен Иса Аль Халифа обсудили ход реализации договоренностей, достигнутых в ходе переговоров в сентябре прошлого года в Москве.', '2017-07-01 18:12:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (176, 6, 'Число пострадавших от удара стихии в Москве увеличилось до 16 человек', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fproisshestviya%2F4380221', '&quot;В Москве пострадали 16 человек, шесть из них находятся в больницах с травами различной степени тяжести, среди них один ребенок&quot;, - сказал собеседник агентства. Десятерым пострадавшим оказана медицинская помощь. Еще три человека пострадали от непогоды в Тульской области.', '2017-07-01 10:39:55+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (5, 3, 'В Москве пустует каждый седьмой квадратный метр офисов', 'https://news.yandex.ru/yandsearch?cl4url=www.arendator.ru%2Fnews%2F155216-v_moskve_pustuet_kazhdyj_sedmoj_kvadratnyj_metr_ofisov%2F', 'В 2017 году поглощение формировалось более равномерно. Несмотря на снижающиеся в последние два года объемы нового строительства, на данный момент на рынке качественных офисных помещений пустуют около 2,9 млн. кв. м площадей (каждый седьмой квадратный метр).', '2017-06-27 18:12:54+04', 2);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (177, 2, 'Лёв не боится серии пенальти в финале Кубка конфедераций с Чили', 'https://news.yandex.ru/yandsearch?cl4url=russian.rt.com%2Fsport%2Fnews%2F404830-lyov-germaniya-chili-penalti', 'Ранее капитан и полузащитник сборной Германии по футболу Юлиан Дракслер поделился мнением об уровне организации Кубка конфедераций 2017 года в России. В финальном матче турнира сыграют сборные Германии и Чили. Встреча пройдёт на стадионе &quot;Санкт-Петербург&quot; 2 июля.', '2017-07-01 18:34:05+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (178, 1, 'Британцу грозит тюрьма за поддержку ополченцев в Донбассе', 'https://news.yandex.ru/yandsearch?cl4url=www.ntv.ru%2Fnovosti%2F1830238%2F', 'В Великобритании суда ожидает 41-летний Бенджамин Стимсон, который высказывался в поддержку ополченцев в Донбассе. 41-летний британец Бенджамин Стимсон был задержан после интервью, которое дал в октябре 2015 года телеканалу ВВС.', '2017-07-01 12:42:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (179, 6, 'МРОТ для россиян вырос на 300 рублей', 'https://news.yandex.ru/yandsearch?cl4url=lenta.ru%2Fnews%2F2017%2F07%2F01%2Fmrot%2F', 'В России с 1 июля 2017 года в силу вступают изменения в закон «О минимальном размере оплаты труда», по которым уровень МРОТ увеличивается с 7500 до 7800 рублей, сообщает ТАСС. Как заявляла вице-премьер Ольга Голодец, зарплату на уровне МРОТ в России получают 4,9 миллиона человек.', '2017-07-01 07:43:25+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (180, 1, 'Медвежонок пришел в магазин на Аляске за конфетами', 'https://news.yandex.ru/yandsearch?cl4url=lenta.ru%2Fnews%2F2017%2F07%2F01%2Falkobear%2F', 'Медвежонок зашел в магазин на Аляске. Видеозапись инцидента опубликовало в субботу, 1 июля, издание Alaska Dispatch News. Зверь подошел к прилавку с конфетами, встал на задние лапы и начал изучать ассортимент.', '2017-07-01 18:04:50+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (181, 5, 'СБУ обвинила спецслужбы РФ в причастности к атаке вируса Petya.A', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fmezhdunarodnaya-panorama%2F4380402', 'Служба безопасности Украины (СБУ) заявила, что установила причастность спецслужб России к атаке вируса Petya.A, от которого пострадали ряд украинских компаний и банков. Об этом в субботу сообщил пресс-центр СБУ.', '2017-07-01 13:32:17+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (182, 6, 'СБУ обвинила спецслужбы РФ в причастности к атаке вируса Petya.A', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fmezhdunarodnaya-panorama%2F4380402', 'Служба безопасности Украины (СБУ) заявила, что установила причастность спецслужб России к атаке вируса Petya.A, от которого пострадали ряд украинских компаний и банков. Об этом в субботу сообщил пресс-центр СБУ.', '2017-07-01 13:32:17+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (54, 3, 'Ипотекой охватят миллион россиян', 'https://news.yandex.ru/yandsearch?cl4url=www.uralinform.ru%2Fnews%2Feconomy%2F275146-ipotekoi-ohvatyat-million-rossiyan%2F', 'Целью проекта является улучшение жилищных условий граждан России, обеспечение высоких темпов ввода жилья и увеличение объемов выдачи ипотечных кредитов. Разработчики проекта планируют к 2020 году довести объемы сдачи &quot;ипотечного&quot; жилья до 100 миллионов квадратных метров.', '2017-06-29 16:43:57+04', 10);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (183, 6, 'МРОТ в России вырос до 7800 рублей в месяц', 'https://news.yandex.ru/yandsearch?cl4url=www.interfax.ru%2Frussia%2F568762', 'В министерстве напомнили, что в России с 1 июля МРОТ вырастет на уровень инфляции - 4%, поднявшись с 7500 до 7800 рублей в месяц. В результате соотношение МРОТ к прожиточному минимуму (ПМ) составит 73%. Последний раз МРОТ повышался годом ранее, 1 июля 2016 года.', '2017-07-01 10:07:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (105, 2, 'России осталось взять финальный аккорд', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F613003', 'Кубок конфедераций, проходящий в России, выходит на завершающую стадию. Два из четырех городов хозяев турнира — Казань и Сочи — уже попрощались с соревнованием ФИФА. Там прошли полуфинальные встречи Португалия–Чили и Германия–Мексика.', '2017-07-01 01:00:01+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (106, 2, '14 сборных хотят базироваться в Сочи во время чемпионата мира — 2018', 'https://news.yandex.ru/yandsearch?cl4url=www.championat.com%2Ffootball%2F_worldcup%2Fnews-2840928-14-sbornyh-hotjat-bazirovatsja-v-sochi-vo-vremja-chempionata-mira-2018.html', '14 потенциальных участников чемпионата мира 2018 года в России выразили ФИФА своё желание базироваться в Сочи во время мундиаля, несмотря на то, что в городе будут только две базы, сообщает ESPN FC. По данным источника, одной из сборных, которая хочет разместиться в Сочи, является команда Германии.', '2017-07-01 14:16:33+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (107, 2, 'Хуан Антонио Пицци: «Хотим победить в финале Кубка конфедераций»', 'https://news.yandex.ru/yandsearch?cl4url=www.ftbl.ru%2Fnews%2F387385%2F', 'Напомним, что сборная Чили сыграет в финале Кубка конфедераций против национальной команды Германии. Встреча состоится 2 июля и начнется в 21:00 по московскому времени.', '2017-07-01 15:21:19+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (108, 2, 'Сантуш назвал правильным решение отпустить Роналду к детям', 'https://news.yandex.ru/yandsearch?cl4url=rg.ru%2F2017%2F07%2F01%2Fsantush-nazval-pravilnym-reshenie-otpustit-ronaldu-k-detiam.html', 'Лидер сборной Португалии по футболу Криштиану Роналду не примет участия в матче Кубка конфедераций за третье место против мексиканцев, так как улетел к новорожденным детям. Главный тренер португальской команды Фернанду Сантуш не сомневается, что принял верное решение, отпустив Роналду.', '2017-07-01 15:15:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (109, 2, 'Система видеоповторов может заработать на матчах РФПЛ после ЧМ-2018', 'https://news.yandex.ru/yandsearch?cl4url=realnoevremya.ru%2Fnews%2F69571-sistema-videopovtorov-mozhet-zarabotat-na-matchah-rfpl-posle-chm-2018', 'Глава РФС Виталий Мутко заявил, что хотел бы после чемпионата мира 2018 года оставить систему видеоповторов (VAR) на всех стадионах, которые будут принимать турнир.', '2017-07-01 16:39:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (110, 2, 'Матч Португалия-Мексика пройдет на стадионе «Открытие Арена»', 'https://news.yandex.ru/yandsearch?cl4url=mos.news%2Fnews%2Fszao%2Fmatch_portugaliya_meksika_proydet_na_stadione_otkrytie_arena%2F', 'В завтрашнем матче Кубка конфедераций за третье встретятся сборные Португалии и Мексики, пишет агентство «Москва».', '2017-07-01 13:35:14+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (8, 5, 'К приезду Путина Ижевск затопило', 'https://news.yandex.ru/yandsearch?cl4url=regnum.ru%2Fnews%2Fpolit%2F2293537.html', 'До приезда Путина в Ижевске прошел ливень и затопил ряд городских улиц.', '2017-06-27 18:30:00+04', 1);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (100, 2, 'Петкович подписал контракт со «Спартаком»', 'https://news.yandex.ru/yandsearch?cl4url=www.gazeta.ru%2Fsport%2Fnews%2F2017%2F07%2F01%2Fn_10249823.shtml', 'Защитник &quot;Црвены Звезды&quot; Марко Петкович перешел в &quot;Спартак&quot;, передает &quot;Р-Спорт&quot;. Серб уже уже прилетел на сбор своего клуба, сообщает официальный сайт красно-белых.', '2017-07-01 18:10:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (101, 2, 'Диего Марадона поздравил Лионеля Месси со свадьбой', 'https://news.yandex.ru/yandsearch?cl4url=rsport.ru%2Ffootball%2F20170701%2F1122380388.html', 'Легенда мирового футбола аргентинец Диего Марадона поздравил своего соотечественника нападающего &quot;Барселоны&quot; Лионеля Месси с прошедшей свадьбой. Свадьба Месси и его возлюбленной Антонеллы Рокуццо состоялась в пятницу в родном городе футболиста – аргентинском Росарио.', '2017-07-01 11:44:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (102, 2, 'Сборную Португалии покинул ещё один игрок', 'https://news.yandex.ru/yandsearch?cl4url=sportfm.ru%2Fnews%2Fsbornuyu-portugalii-pokinul-eshchye-odin-igrok.html', 'Вчера утром защитник Рафаэл Геррейру покинул расположение сборной Португалии и улетел к себе на родину. Как сообщает «Спорт-экспресс», такое решение игрок принял в связи с полученной травмой, которая не позволила бы ему выступить в матче за третье место.', '2017-07-01 12:36:47+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (103, 2, 'ЦСКА и «Локомотив» нацелились на полузащитника «Эшторила»', 'https://news.yandex.ru/yandsearch?cl4url=sportfm.ru%2Fnews%2Ftsska-i-lokomotiv-natselilis-ni-poluzashchitnika-eshtorila.html', 'По информации A Bola, представители ЦСКА и «Локомотива» ведут борьбу за право подписания контракта с 21-летним полузащитником. Однако сам Индио склоняется к тому, чтобы перейти в швейцарский «Сьон». Отметим, что руководство «Эшторила» готово продать Матеуса Индио за €3,5 млн.', '2017-07-01 16:45:18+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (104, 2, 'Чемпионат по футболу для дружбы впервые пройдет в Санкт-Петербурге', 'https://news.yandex.ru/yandsearch?cl4url=nsn.fm%2Fsport%2Fchempionat-po-futbolu-dlya-druzhby-vpervye-proydet-v-sankt-peterburge.html', 'В Санкт-Петербурге в рамках Кубка конфедераций впервые пройдет Чемпионат по футболу для дружбы. В нем примут участие юные футболисты реализуемого «Газпромом» проекта. Из общего числа участников будут составлены 8 Международных сборных дружбы, которые продемонстрируют свои способности в футболе.', '2017-07-01 13:09:54+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (116, 1, 'WP рассказала, почему Меркель проголосовала против однополых браков', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497659088.html', 'Газета The Washington Post объяснила, почему Ангела Меркель, известная &quot;приверженностью либеральным ценностям&quot;, проголосовала против законопроекта об однополых браках.', '2017-07-01 16:34:10+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (117, 1, 'В Киеве прокомментировали арест украинского военного в Италии', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497659080.html', '&quot;Генпрокуратура удивлена арестом в Италии украинского солдата Маркива Виталия, по подозрению в убийстве фоторепортера Андреа Рокелли вблизи города Славянск в мае 2014 года, выдвинутого прокуратурой города Павия&quot;, — написал Енин на своей странице в Facebook.', '2017-07-01 16:34:02+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (7, 4, '30 июня в Пензенской области объявлено днем без аборта', 'https://news.yandex.ru/yandsearch?cl4url=www.penzainform.ru%2Fnews%2Fsocial%2F2017%2F06%2F28%2F30_iyunya_v_penzenskoj_oblasti_obyavleno_dnem_bez_aborta.html', 'В пятницу, 30 июня, в Пензенской области вновь пройдет день без аборта. Все учреждения родовспоможения региона, в том числе и частные клиники, не будут выполнять прерывания беременности по желанию женщины.', '2017-06-28 11:03:53+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (90, 6, 'В Белом Доме на Трампа дважды чуть не уронили лампу', 'https://news.yandex.ru/yandsearch?cl4url=inforeactor.ru%2F84367-v-belom-dome-na-trampa-dvazhdy-chut-ne-uronili-lampu', 'В Вашингтоне в официальным визитом находится президент Южной Кореи Мун Чжэ Ин. Во время подготовки к официальным съемкам рукопожатия Дональда Трампа и Мун Чжэ Ина, корейские журналисты дважды едва не перевернули настольную лампу, стоящую на столе рядом с американским президентом.', '2017-07-01 10:22:58+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (111, 2, 'Президент ФИФА оценил Кубок конфедераций в России', 'https://news.yandex.ru/yandsearch?cl4url=lenta.ru%2Fnews%2F2017%2F07%2F01%2Finfantinni%2F', 'Проходящий в России Кубок конфедераций стал большим успехом. Об этом заявил президент Международной федерации футбола (ФИФА) Джанни Инфантино. Его слова приводит «Советский спорт» в субботу, 1 июля.', '2017-07-01 13:11:48+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (112, 2, 'Марадона назвал Путина своим кумиром', 'https://news.yandex.ru/yandsearch?cl4url=lenta.ru%2Fnews%2F2017%2F07%2F01%2Fmaradonaputin%2F', 'Бывший нападающий сборной Аргентины Диего Марадона назвал президента России Владимира Путина своим кумиром. Слова футболиста приводит «Советский спорт».', '2017-07-01 12:26:22+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (113, 2, 'Марадона назвал Путина феноменом и захотел тренировать сборную России', 'https://news.yandex.ru/yandsearch?cl4url=www.vesti.ru%2Fdoc.html%3Fid%3D2905141', 'Недавно Диего Марадона говорил, что собирается поучаствовать в организации чемпионата мира по футболу, который пройдет в России в 2018 году — причем сделает это по личной просьбе российского президента Владимира Путина.', '2017-07-01 12:15:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (118, 1, 'В ФБР не считают стрельбу в нью-йоркской больнице терактом', 'https://news.yandex.ru/yandsearch?cl4url=russian.rt.com%2Fworld%2Fnews%2F404717-fbr-strelba-terrorizm', 'Представители Федерального бюро расследований (ФБР) заявили, что пока нет оснований связывать стрельбу в больнице в Бронксе с терроризмом. Об этом говорится в сообщении в Twitter нью-йоркского отделения ФБР.', '2017-07-01 05:57:15+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (114, 2, 'Мутко: около 26 тыс. иностранцев получили паспорта болельщиков', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F612734', 'Вице-премьер РФ, председатель оргкомитета «Россия-2018» Виталий Мутко сообщил, что паспорта болельщиков получили около 26 тыс. иностранных болельщиков. Мутко рассказал на пресс-конференции, что система безопасности на Кубке конфедераций в принимающих матчи городах работает безукоризненно.', '2017-06-29 21:26:18+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (115, 1, 'В Словакии 25 немецких туристов пострадали в ДТП', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497658855.html', 'Неподалеку от города Трнава на западе Словакии в субботу утром съехал с дороги и упал на бок автобус, в котором находились 52 немецких туриста, 25 из них получили ранения разной тяжести, сообщила журналистам представитель республиканского управления &quot;Скорой помощи&quot; Зузана Фуркасова.', '2017-07-01 16:17:59+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (119, 1, 'В Неваде началась продажа марихуаны в рекреационных целях', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497651469.html', 'В американской Неваде в субботу началась продажа марихуаны, этот штат стал пятым в США, где продают наркотическое средство в рекреационных целях, передает агентство Ассошиэйтед Пресс. Ранее в ноябре избиратели штата одобрили использование марихуаны в так называемых &quot;развлекательных&quot; целях.', '2017-07-01 12:21:59+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (169, 2, 'Мутко: Матчи Кубка конфедераций посетили 600 тысяч человек', 'https://news.yandex.ru/yandsearch?cl4url=www.tatar-inform.ru%2Fnews%2F2017%2F07%2F01%2F560794%2F', 'Мутко сообщил, что все билеты на полуфинал и финал уже проданы, пишет Life. Мутко поблагодарил всех посетивших матчи Кубка конфедераций за небывалую атмосферу.', '2017-07-01 16:14:27+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (121, 1, 'Пентагон отложил на полгода прием трансгендеров в армию', 'https://news.yandex.ru/yandsearch?cl4url=echo.msk.ru%2Fnews%2F2010462-echo.html', 'В прошлом году тогдашний министр обороны Эштон Картер объявил об отмене запрета с 1 июля. Теперь запрет планируется снять 1 января.', '2017-07-01 11:30:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (122, 1, 'Спецслужбы США предупредили энергетический сектор о хакерских атаках', 'https://news.yandex.ru/yandsearch?cl4url=360tv.ru%2Fnews%2Fspecsluzhby-ssha-predupredili-121980%2F', 'Федеральное бюро расследований (ФБР) и Министерство внутренней безопасности США неофициально предупредили американские компании энергетической, ядерной и промышленной сферы о возможных хакерских атаках.', '2017-07-01 09:39:32+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (123, 3, 'Банк «Открытие» объявил о беспрецедентном снижении ставок по ипотеке', 'https://news.yandex.ru/yandsearch?cl4url=newsprom.ru%2Fnews%2FEkonomika%2F231901.html', '26 июня 2017 года банк «Открытие» снизил размер первоначального взноса и процентные ставки по всем программам ипотечного кредитования. На сегодняшний день предложение «Открытия» одно из самых привлекательных на российском рынке.', '2017-06-30 10:35:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (12, 2, 'Известный футболист Лионель Месси женился на подруге детства', 'https://news.yandex.ru/yandsearch?cl4url=rg.ru%2F2017%2F07%2F01%2Fizvestnyj-futbolist-lionel-messi-zhenilsia-na-podruge-detstva.html', 'На свадьбе присутствовали 260 гостей. Вместо подарков им предложили сделать пожертвования в благотворительный фонд, созданный для оказания помощи детям. РИА Новости отмечает, что Месси и Рокуццо знакомы с детства, а встречаться начали во второй половине 2000-х, сейчас у пары два сына.', '2017-07-01 05:28:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (124, 3, 'Цены на вторичное жильё и новостройки в Калуге снижаются', 'https://news.yandex.ru/yandsearch?cl4url=www.vest-news.ru%2Fnews%2F98832', 'Снижаются цены главным образом на трёхкомнатные и двухкомнатные квартиры. А вот однокомнатные, напротив, слегка подорожали. На убыль за прошедшую семидневку пошли и цены на квадратные метры в новостройках.', '2017-06-28 16:13:04+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (125, 3, 'Банк ТКБ улучшил условия по ипотеке', 'https://news.yandex.ru/yandsearch?cl4url=www.ludiipoteki.ru%2Fnews%2Findex%2Fthemes%2F271%2Fentry%2Fbank-tkb-uluchshil-usloviya-po-ipoteke%2F', 'Банк ТКБ улучшил условия по ипотечному кредитованию.', '2017-06-30 14:33:42+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (18, 2, '«Локомотив» объявил о трансфере Соломона Кверквелии', 'https://news.yandex.ru/yandsearch?cl4url=www.sportsdaily.ru%2Fnews%2Flokomotiv-obyavil-o-transfere-solomona-kverkvelii', 'Защитник Соломон Кверквелия официально стал игроком «Локомотива», сообщает официальный сайт московского клуба. В минувшем сезоне Кверквелия выступал за «Локомотив» на правах аренды. Сегодня же был оформлен полноценный трансфер — 25-летний игрок подписал контракт до 2021 года.', '2017-07-01 00:20:48+04', 10);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (6, 4, 'С начала сезона туляки жаловались на укусы клещей 1150 раз', 'https://news.yandex.ru/yandsearch?cl4url=www.tula.aif.ru%2Fhealth%2Fs_nachala_sezona_tulyaki_zhalovalis_na_ukusy_kleshchey_1150_raz', 'С начала сезона с укусами клещей в больницы обратилось 1150 человек (из них детей - 406), сообщает региональный Роспотребнадзор. По данным еженедельного мониторинга в период с 19 по 25 июня зафиксировано 203 случая присасывания клеща. Среди обратившихся в больницы - 61 ребенок.', '2017-06-28 08:54:10+04', 10);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (120, 1, 'В Токио вступил в силу запрет на свидания за деньги для школьниц', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fobschestvo%2F4380109', 'Запрет на работу в сфере свиданий за деньги вступил в субботу в Токио для школьниц моложе 18 лет. Соответствующее постановление было принято в пятницу государственным законодательным собранием японской столицы.', '2017-07-01 04:33:36+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (126, 3, 'За полтора года была продана только одна квартира на Остоженке', 'https://news.yandex.ru/yandsearch?cl4url=www.vesti.ru%2Fdoc.html%3Fid%3D2904959', 'Только одна квартира на первичном рынке элитного желя в районе Остоженки в Москве была продана за полтора года, сообщает пресс-служба Contact Real Estate. Сделка состоялась в первом полугодии 2017-го. В начале нулевых район был лидером на первичном рынке элитного жилья.', '2017-06-30 17:10:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (127, 4, 'Какие продукты в России едят неправильно', 'https://news.yandex.ru/yandsearch?cl4url=news.nashbryansk.ru%2F2017%2F07%2F01%2Frussia-and-world%2Fkakie-produktyi-edyat-nepravilno%2F', 'Наши российские привычки употреблять некоторые продукты, например, есть отдельные фрукты без кожуры или пить чай с молоком, могут удивить многих диетологов. Издание «Кириллица» попробовало разобраться, в чем там дело.', '2017-07-01 09:05:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (128, 4, 'В алтайском перинатальном центре «ДАР» рождены уже 500 детей', 'https://news.yandex.ru/yandsearch?cl4url=regnum.ru%2Fnews%2Feconomy%2F2295285.html', 'Долгих 10 лет жители Алтайского края Владимир и Глория Елфутины провели в ожидании своего первенца. И вот 29 июня в 7.08 малыш смог появиться на свет. Это радостное событие произошло в родовом отделении краевого перинатального центра «ДАР».', '2017-07-01 10:20:39+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (10, 2, 'Мутко: украшением КК-2017 стала атмосфера на стадионах во всех городах', 'https://news.yandex.ru/yandsearch?cl4url=www.championat.com%2Ffootball%2Fnews-2840846-mutko-ukrasheniem-kk-2017-stala-atmosfera-na-stadionah-vo-vseh-gorodah.html', 'Все игры были великолепные, и мы получили огромное удовольствие от игры команд. Украшением турнира стала атмосфера на стадионах во всех городах. Благодарю всех болельщиков, которые уже посетили и ещё посетят наши матчи.', '2017-07-01 12:24:01+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (13, 2, 'Марадона: Путин представляет «высшую лигу», а Трамп — «герой комикса»', 'https://news.yandex.ru/yandsearch?cl4url=www.ntv.ru%2Fnovosti%2F1830201%2F', 'Легендарный аргентинский футболист Диего Марадона заявил, что президент России Владимир Путин для него — феномен.', '2017-07-01 11:48:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (16, 2, 'Миллер: Кто критикует «Зенит-Арену», тот просто ей завидует', 'https://news.yandex.ru/yandsearch?cl4url=www.spb.kp.ru%2Fonline%2Fnews%2F2793294%2F', 'Море критики, со всех сторон обрушившееся на достроенный стадион на Крестовском острове, может быть банальной завистью. Такое объяснение предложил председатель правления компании &quot;Газпром&quot; Алексей Миллер.', '2017-06-30 22:53:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (19, 2, 'На финал Кубка конфедераций продано уже 53 тыс. билетов', 'https://news.yandex.ru/yandsearch?cl4url=www.business-gazeta.ru%2Fnews%2F350261', 'На финальный матч Кубка конфедераций — 2017, который пройдет в Санкт-Петербурге 2 июля, продано уже 53 тыс. билетов, заявил вице-губернатор Санкт-Петербурга Владимир Кириллов. В решающем матче встретятся команды Чили и Германии.', '2017-06-30 19:40:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (20, 2, 'Капитан сборной Германии поблагодарил россиян за Кубок конфедераций', 'https://news.yandex.ru/yandsearch?cl4url=www.vz.ru%2Fnews%2F2017%2F6%2F30%2F876849.html', 'Капитан сборной Германии по футболу Юлиан Дракслер в открытом письме поблагодарил организаторов Кубка конфедераций и российских болельщиков за проведение турнира.', '2017-06-30 23:04:02+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (21, 2, 'Шторм не повлияет на качество газона «Открытие Арены»', 'https://news.yandex.ru/yandsearch?cl4url=www.goalbox.ru%2F2017%2F06%2F30%2Fshtorm-ne-povliyaet-na-kachestvo-gazona-otkrytie-areny%2F', 'Всё будет нормально, – уверенно заявил Мутко, а его слова приводит ТАСС.', '2017-06-30 18:27:36+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (22, 2, 'Игорь Лебедев признал неуместными свои слова в адрес Юрия Жиркова', 'https://news.yandex.ru/yandsearch?cl4url=www.vesti.ru%2Fdoc.html%3Fid%3D2904949', 'Депутат Государственной дума, член исполкома РФС Игорь Лебедев признал, что был неправ, допустив грубые выражения в адрес полузащитника сборной России Юрия Жиркова. Лебедев назвал свои высказывания неуместными.', '2017-06-30 16:53:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (23, 2, 'Халк и Виллаш-Боаш дисквалифицированы на 2 игры за поддержку Оскара', 'https://news.yandex.ru/yandsearch?cl4url=www.soccer.ru%2Fnews%2F995992.shtml', 'Футболист и тренер, знакомые российскому болельщику по выступлениям и работе в &quot;Зените&quot;, получили наказания за поддержку полузащитника &quot;Шанхай СИПГ&quot; Оскара, который ранее получил восемь матчей дисквалификации за участие в массовой драке во время матча чемпионата страны с «Гуанчжоу Фули».', '2017-06-30 18:57:40+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (25, 1, 'Британцу грозит тюремный срок за поддержку ополченцев в Донбассе', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F613325', 'Британцу Бенджамину Стимсону грозит тюремное заключение за поддержку ополченцев в Донбассе. Как сообщает газета The Times, 41-летний Стимсон провел четыре месяца в 2015 году в Донбассе. В октябре 2015 года он дал интервью BBC, в котором заявил, что гордится тем, что сделал.', '2017-07-01 05:45:31+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (86, 6, 'В New York Post твитам Трампа посвятили статью из трех слов', 'https://news.yandex.ru/yandsearch?cl4url=www.rbc.ru%2Frbcfreenews%2F5957255d9a79475faaf1d2a1', 'В номере газеты New York Post от 30 июня вышла статья о твитах президента США Дональда Трампа.', '2017-07-01 08:53:58+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (24, 2, 'Кириллов: Город не получает доходов от продаж во время Кубка конфедераций', 'https://news.yandex.ru/yandsearch?cl4url=www.fontanka.ru%2F2017%2F06%2F30%2F068%2F', 'Напомним, в Петербурге на текущий момент прошло три матча группового этапа, включая матч-открытие. В воскресенье, 2 июля, в Северной столице также пройдет финал Кубка конфедераций Германия – Чили. Как ранее заявил Владимир Кириллов, на стадионе «Санкт-Петербург» ожидается аншлаг.', '2017-06-30 15:47:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (26, 1, 'Медведь зашел в алкогольный магазин на Аляске', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F613342', 'На Аляске бурый медведь зашел в алкогольный магазин, сообщает BBC. Из всего ассортимента косолапому больше всего приглянулся стенд со сладостями. Владелец магазина Роджер Тибодо не испугался и побежал прогонять незваного гостя.', '2017-07-01 08:45:13+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (27, 1, 'В Токио школьницам запретили ходить на свидания за деньги', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497645820.html', 'В настоящее время в Токио, согласно информации токийской полиции, существует около 110 коммерческих предприятий и около 30 незарегистрированных компаний, которые предлагают услуги по организации свиданий со школьницами. Очень часто на такие свидания направляют девушек младше 18 лет.', '2017-07-01 08:13:40+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (28, 1, 'Минобороны США на полгода отложило прием трансгендеров в армию', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497644976.html', 'По данным агентства, решение по данному вопросу отложено до 1 января. Запрет трансгендерам на службу в американской армии был снят при администрации экс-президента США Барака Обамы.', '2017-07-01 06:03:14+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (29, 1, 'ФБР предупредило энергетический сектор об угрозе кибератак', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497645073.html', 'ФБР и министерство внутренней безопасности США предупредили американские энергетические компании, что энергетический сектор традиционно является объектом кибератак, с мая фиксируются фишинговые атаки.', '2017-07-01 06:24:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (30, 1, 'Один человек погиб в результате стрельбы в Нью-Йорке', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497642543.html', 'Один человек погиб, еще несколько ранены при стрельбе в нью-йоркской больнице, нападавший покончил с собой. Об этом сообщил мэр города Билл де Блазио. Как заявил градоначальник, погибший был врачом.', '2017-07-01 02:05:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (31, 1, 'В Испании задержали предполагаемого боевика ИГ', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fmezhdunarodnaya-panorama%2F4380130', 'Сотрудники Гражданской гвардии Испании задержали в городе Малага на юге страны мужчину, подозреваемого в участии в боевых действиях в Сирии на стороне террористической группировки &quot;Исламское государство&quot; (ИГ, запрещена в РФ).', '2017-07-01 06:22:59+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (32, 1, 'Лидер Южной Кореи назвал условия для начала диалога с КНДР', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497643590.html', 'Президент Республики Корея Мун Чжэ Ин во время выступления в Вашингтоне назвал некоторые условия, которые могут помочь начать диалог с северным соседом.', '2017-07-01 03:24:11+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (33, 1, 'Легкомоторный самолёт упал на шоссе возле Лос-Анджелеса', 'https://news.yandex.ru/yandsearch?cl4url=polit.info%2F347866-legkomotornyi-samolet-upal-na-shosse-vozle-los-andzhelesa', 'До взлетно-посадочной полосы самолет не дотянул, рухнув на шоссе, после чего взорвался.', '2017-07-01 02:47:02+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (34, 1, 'Белый дом обнародовал информацию о зарплатах в администрации Трампа', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497646074.html', 'Больше всех среди членов администрации получает старший политический советник президента Марк Хаус. Глава Национального экономического совета при Белом доме Гэри Кон зарабатывает меньше всех. Ранее Трамп также опубликовал информацию о своих доходах за 2016 год.', '2017-07-01 08:42:57+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (35, 1, 'Неизвестный сломал бедро российскому туристу в отеле на Кипре', 'https://news.yandex.ru/yandsearch?cl4url=www.kp.ru%2Fonline%2Fnews%2F2793306%2F', 'В одном из отелей кипрского города Ларнака между 47-летним российским туристом и другим постояльцем гостиницы произошел конфликт, который закончился дракой. Иностранец неожиданно набросился на нашего соотечественника и начал его избивать.', '2017-07-01 00:05:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (36, 1, 'Facebook меняет алгоритм борьбы со спамом', 'https://news.yandex.ru/yandsearch?cl4url=www.kommersant.ru%2Fdoc%2F3341844', 'Социальная сеть Facebook совершенствует методы борьбы со спамом. Обновление должно уменьшить «некачественные» ссылки в ленте новостей.', '2017-07-01 05:37:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (37, 1, 'Трамп объявил о сделке по поставкам Южной Корее СПГ на сумму $25 млрд', 'https://news.yandex.ru/yandsearch?cl4url=www.rbc.ru%2Frbcfreenews%2F59568fa49a794739e8d4ebfd', 'Президент США Дональд Трамп объявил о начале поставок американской компанией Cheniere сжиженного природного газа (СПГ) в Южную Корею в рамках сделки на $25 млрд, сообщает агентство Yonhap.', '2017-06-30 22:24:34+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (38, 1, 'Суд не вернул Полу Маккартни права на песни The Beatles', 'https://news.yandex.ru/yandsearch?cl4url=tsargrad.tv%2Fnews%2Fsud-ne-vernul-polu-makkartni-prava-na-pesni-the-beatles_72356', 'Экс-солисту группы The Beatles Полу Маккартни суд отказал в возврате авторских прав на те песни The Beatles, которые были написаны им вместе с Джоном Ленноном. Суд Южного округа штата Нью-Йорк отклонил иск Маккартни. Судья добавил, что вернется к рассмотрению дела позднее.', '2017-06-30 23:11:36+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (39, 1, 'Соцсети в Германии оштрафуют на €50 млн за недопустимый контент', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F613258', 'Бундестаг принял закон, предусматривающий штрафы за недопустимый контент в социальных сетях. Как сообщает BBC, администраторов соцсетей обязали удалить сообщения с недопустимым контентом до октября 2017 года.', '2017-06-30 23:38:56+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (42, 3, 'Новостройки подешевели в большинстве российских городов', 'https://news.yandex.ru/yandsearch?cl4url=www.vesti.ru%2Fdoc.html%3Fid%3D2904538', 'С начала 2017 года в 23 российских городах новостройки подорожали, в 46 – подешевели. При этом в 11 населенных пунктах зафиксированы колебания в пределах 1 процента.', '2017-06-29 17:55:16+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (43, 3, 'Полгода ждать: рынок жилья возвращается к докризисному состоянию', 'https://news.yandex.ru/yandsearch?cl4url=realnoevremya.ru%2Farticles%2F69526-rynok-zhilya-vozvraschaetsya-k-dokrizisnomu-sostoyaniyu', 'Ситуация на рынке жилья остается сложной и нестабильной, констатировала Нина Горюнова, главный редактор &quot;Эха Москвы в Казани&quot;, начиная передачу. Риелторы говорят о затоваривании рынка, низком спросе.', '2017-06-30 23:25:02+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (44, 3, 'В ЖК «Маяковский» снижены ставки от банка «Уралсиб»', 'https://news.yandex.ru/yandsearch?cl4url=mos.news%2Fnews%2Fnedvizhimost%2Fv_zhk_mayakovskiy_snizheny_stavki_ot_banka_uralsib%2F', 'Наряду с привлекательными ипотечными ставками в строящемся ЖК «Маяковский» покупатели могут также воспользоваться услугой банка - «Ипотечные каникулы».', '2017-06-29 15:58:48+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (46, 3, 'Индекс недвижимости «Абирега» – средняя цена квадратного метра в Воронеже снизилась из-за роста предложения', 'https://news.yandex.ru/yandsearch?cl4url=abireg.ru%2Fn_61612.html', 'Эксперты «Трансферта» пояснили, что снижение произошло из-за значительного объема предложений жилья на рынке. Как и в начале года, во втором квартале 2017 года стоимость вторичного жилья в Воронеже продолжает быть выше стоимости «первички» – 43,18 тыс. рублей против 42,25 тыс. рублей.', '2017-06-30 19:15:49+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (47, 3, 'ВТБ и АИЖК совместно займутся развитием рынка доходных домов', 'https://news.yandex.ru/yandsearch?cl4url=newdaynews.ru%2Frealty%2F607471.html', 'В свою очередь АИЖК планирует предоставить финансирование строительства данных проектов. Как сообщили в пресс-службе ВТБ, стороны также рассмотрят возможность создания управляющей компании для эксплуатации проектов стандартного арендного жилья в регионах.', '2017-06-30 16:08:41+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (48, 3, 'Хотели обмануть государство, а обманули себя', 'https://news.yandex.ru/yandsearch?cl4url=gov.cap.ru%2Finfo.aspx%3Fgov_id%3D589%26id%3D3609534', 'Ловушкой для продавца может стать желание сэкономить на налогах. Однако обман государства сродни самообману.', '2017-06-30 15:39:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (50, 3, 'Выгодно ли в Красноярске купить квартиру в новостройках этим летом?', 'https://news.yandex.ru/yandsearch?cl4url=www.krsk.kp.ru%2Fdaily%2F26699.7%2F3723199%2F', 'Все застройщики Красноярска сегодня имеют договоренность с банками. На основании этого можно сделать вывод, что покупать новостройки в Красноярске выгодно именно сейчас.', '2017-06-30 16:39:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (40, 3, 'Цены на жилье в Великобритании в июне выросли на 1,1 п.п. - Nationwide', 'https://news.yandex.ru/yandsearch?cl4url=realty.interfax.ru%2Fru%2Fnews%2Farticles%2F83049', 'Аналитики прогнозировали повышение первого показателя всего на 0,1%, второго - на 1,9%. &quot;Цены на жилье в Великобритании вновь начали расти, нивелируя снижение, в течение трех предыдущих месяцев&quot;, - прокомментировал главный экономист Nationwide Роберт Гарднер.', '2017-06-28 15:10:44+04', 9);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (49, 3, 'Саратов занял 11 место по стоимости жилья на вторичном рынке', 'https://news.yandex.ru/yandsearch?cl4url=echosar.ru%2Fnews%2Fnews_11519.html', 'В целом, эксперты ожидают оживления рынка до конца года, в связи с возобновлением роста реальных доходов населения. Напомню, согласно статистике Саратовстата стоимость на жилье падает уже два года подряд.', '2017-06-28 11:53:00+04', 10);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (45, 3, 'АИЖК прогнозирует снижение ипотечных ставок до уровня европейских в ближайшие годы', 'https://news.yandex.ru/yandsearch?cl4url=www.domostroynn.ru%2Fnovosti%2Frynok-nedvizhimosti%2Faizhk-prognoziruet-snizhenie-ipotechnyh-stavok-na-urovne-evropeyskih-v-blizhayshie-gody', 'Специалисты агентства ипотечного жилищного кредитования (АИЖК) прогнозируют возможное снижение ипотечных ставок в России до европейского уровня.', '2017-06-28 11:41:40+04', 2);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (51, 3, 'Прио-Внешторгбанк снизил ставку по «Образовательному» кредиту', 'https://news.yandex.ru/yandsearch?cl4url=www.banki.ru%2Fnews%2Flenta%2F%3Fid%3D9840340%26r1%3Drss%26r2%3Dyandex.news', 'Прио-Внешторгбанк обновил условия предоставления «Образовательного» кредита.', '2017-06-30 17:00:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (53, 3, 'Москвичи заключили рекордное количество ипотечных сделок', 'https://news.yandex.ru/yandsearch?cl4url=newizv.ru%2Fnews%2Fsociety%2F29-06-2017%2Fmoskvichi-zaklyuchili-rekordnoe-kolichestvo-ipotechnyh-sdelok', 'Ранее сообщалось, что к концу мая 2017 года банки выдали рекордное количество ипотечных займов на сумму 140 млрд руб.', '2017-06-29 14:15:03+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (55, 4, 'Ведущие онкологи Северо-Запада посетили Коми', 'https://news.yandex.ru/yandsearch?cl4url=www.bnkomi.ru%2Fdata%2Fnews%2F64760%2F', 'Фото пресс-службы Минздрава Коми В ходе встречи обсуждались актуальные вопросы, касающиеся организации онкологической помощи в республике, маршрутизации пациентов от первичных онкологических кабинетов в районах до специализированных отделений онкодиспансера и обеспеченности высокотехнологическим оборудованием.', '2017-06-28 18:48:04+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (56, 4, 'В Калужской области выявлено 123 новых случая заражения ВИЧ-инфекцией', 'https://news.yandex.ru/yandsearch?cl4url=znamkaluga.ru%2Findex.php%2F17492-v-kaluzhskoj-oblasti-vyyavleno-123-novykh-sluchaya-zarazheniya-vich-infektsiej', 'Медицинской реабилитацией наркопотребителей занимаются два государственных специализированных учреждения. В этом году помощь здесь получают 120 граждан.', '2017-06-30 16:59:24+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (57, 4, 'Диетологи рассказали о пользе кабачков для здоровья', 'https://news.yandex.ru/yandsearch?cl4url=actualnews.org%2Fnauka%2F182409-dietologi-rasskazali-o-polze-kabachkov-dlya-zdorovya.html', 'Диетологи рассказали о пользе, оказываемой на здоровье человека кабачками.', '2017-07-01 08:29:55+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (59, 4, 'Девятнадцать жителей Тюменской области заболели клещевым энцефалитом', 'https://news.yandex.ru/yandsearch?cl4url=t-l.ru%2F228834.html', 'На 27 июня зарегистрировано 19 случаев заболевания клещевым энцефалитом, из них один ребенок. Клещевой боррелиоз подтвержден у 15 взрослых и двух детей. Наиболее эффективным методом профилактики клещевого энцефалита является вакцинация.', '2017-06-30 19:16:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (52, 3, 'Оплату концессий из бюджета отправят в будущее', 'https://news.yandex.ru/yandsearch?cl4url=www.kommersant.ru%2Fdoc%2F3338100', 'Идея возникла после споров службы с Минэкономики и Минтрансом из-за отмены конкурса на строительство трассы в Башкирии — это поставило под сомнение уже заключенные и будущие подобные соглашения.', '2017-06-29 02:05:00+04', 1);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (62, 4, 'Во Франции обнаружили очаг вируса птичьего гриппа H5N8', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170630%2F1497640542.html', 'Очаг высокоактивного вируса птичьего гриппа H5N8 обнаружен в коммуне Брийон на севере Франции, говорится в заявлении министерства сельского хозяйства и продовольствия страны. Как говорится в заявлении, вирус был обнаружен в пятницу 30 июня на одном из птичьих дворов коммуны.', '2017-07-01 00:03:25+04', 10);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (61, 4, 'Эксперты назвали 5 самых неподходящих продуктов для утоления жажды', 'https://news.yandex.ru/yandsearch?cl4url=oane.ws%2F2017%2F07%2F01%2Fnazvany-5-samyh-nepodhodyaschih-produktov-dlya-utoleniya-zhazhdy.html', 'Солености Почти во всех упакованных продуктах содержится соль, ведь она используется в качестве консерванта. Когда человек употребляет соленую пищу, клетки организма сигнализируют о жажде, так как соль выводит воду из клеток и вызывает их обезвоженность.', '2017-07-01 01:30:37+04', 10);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (58, 4, 'Челябинский врач поставил на ноги пациентку с патологией', 'https://news.yandex.ru/yandsearch?cl4url=vistanews.ru%2Fsociety%2F154199', 'В Челябинске врач сумел излечить женщищу со сложной патологией. Об этом журналистам поведала пресс-служба Министерства Здравоохранения. Как сообщается, в один день в местное травматологическое отделение областной больницы обратилась 37-летняя местная жительница с жалобами на боль в ногах.', '2017-07-01 11:35:15+04', 10);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (60, 4, 'В трех городах Южного Урала объявлены неблагоприятные метеоусловия', 'https://news.yandex.ru/yandsearch?cl4url=www.nakanune.ru%2Fnews%2F2017%2F06%2F30%2F22474822%2F', 'В трех городах Южного Урала до вечера субботы объявлены неблагоприятные метеоусловия первой степени опасности. Об этом Накануне.RU сообщили в пресс-службе регионального ГУ МЧС. Так, с 19 часов 30 июня до 19 часов 1 июля ожидаются НМУ первой степени опасности в Сатке, Карабаше и Челябинске.', '2017-06-30 16:17:00+04', 10);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (63, 4, 'Попугай-эпилептик удивил ветеринаров в Ростове', 'https://news.yandex.ru/yandsearch?cl4url=www.5-tv.ru%2Fnews%2F137814%2F', 'Врачи поставили попугаю диагноз — эпилепсия. Также специалисты установили причину редкой, для попугая, болезни. Она вызвана стрессом, так как до своего нынешнего хозяина попугай Кеша сменил уже не одну семью.', '2017-06-30 23:55:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (64, 4, 'В Башкирии по вине врачей новорожденный ребенок впал в кому', 'https://news.yandex.ru/yandsearch?cl4url=sputnik.fm%2Fnews%2F26913_v_bashkirii_po_vine_vrachej_novorozhdennyj_rebenok_vpal_v', 'В Башкирии родители новорожденного ребенка обвиняют врачей в ошибке, которая привела к трагедии. Во время родов малыш получил травму и впал в кому. 9 мая в Дюртюлях в семье Снежаны и Ильяса Гарифуллиных родился первенец Тимур.', '2017-07-01 09:03:24+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (65, 4, 'В Великобритании младенца отключат от аппарата жизнеобеспечения вопреки воле родителей', 'https://news.yandex.ru/yandsearch?cl4url=tsargrad.tv%2Fnews%2Fv-velikobritanii-mladenca-otkljuchat-ot-apparata-zhizneobespechenija-vopreki-vole-roditelej_72326', 'В Лондоне вопреки воле родителей отключат от аппарата жизнеобеспечения годовалого Чарли Гарда.', '2017-06-30 21:06:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (66, 4, 'В Архангельской области начали внедрять электронные больничные', 'https://news.yandex.ru/yandsearch?cl4url=www.arh.aif.ru%2Fsociety%2Fv_arhangelskoy_oblasti_nachali_vnedryat_elektronnye_bolnichnye', 'С завтрашнего дня в Поморье начнут выдавать электронные больничные. При этом любой сможет выбрать, какой бланк ему оформить в поликлинике: бумажный или электронный.', '2017-06-30 16:52:07+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (67, 4, 'Среднеахтубинцы смогут лечить зубы, не выезжая из района', 'https://news.yandex.ru/yandsearch?cl4url=vpravda.ru%2Fobshchestvo%2Fsredneahtubincy-smogut-lechit-zuby-ne-vyezzhaya-iz-rayona-41782', 'Специализированные кабинеты работают в самой Средней Ахтубе, Краснослободске, хуторах Бурковский и Клетский, в поселке Красный Октябрь и селе Рахинка. Теперь жители могут получать квалифицированную стоматологическую помощь, не выезжая за пределы района.', '2017-06-30 19:59:58+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (68, 4, 'Подавший в отставку после жалобы Путину главврач передумал увольняться', 'https://news.yandex.ru/yandsearch?cl4url=www.rbc.ru%2Frbcfreenews%2F59563ce99a79470725da8638', 'В социальной сети &quot;ВКонтакте&quot; была создана группа против увольнения главврача. В поддержку обращения к Юрию Ширяеву «пересмотреть свое решение, отозвать заявление и вместе со своей командой продолжить работу в объединенной больнице» проголосовали более 10600 человек.', '2017-06-30 16:19:11+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (70, 5, 'В Раде предложили альтернативу визовому режиму с Россией', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497647692.html', 'Депутат Верховной Рады Антон Геращенко считает, что вместо визового режима с Россией нужно ввести регистрацию приезжих россиян на &quot;специальных сайтах&quot;. Об этом он заявил в эфире канала &quot;112 Украина&quot;.', '2017-07-01 10:24:41+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (71, 5, 'Более 500 мотострелков были подняты по учебной тревоге под Волгоградом', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Farmiya-i-opk%2F4380169', 'Более 500 военнослужащих мотострелкового соединения были подняты в субботу по учебной тревоге в Волгоградской области, сообщили в пресс-службе Южного военного округа.', '2017-07-01 08:21:35+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (72, 5, 'В New York Post твитам Трампа посвятили статью из трех слов', 'https://news.yandex.ru/yandsearch?cl4url=www.rbc.ru%2Frbcfreenews%2F5957255d9a79475faaf1d2a1', 'В номере газеты New York Post от 30 июня вышла статья о твитах президента США Дональда Трампа.', '2017-07-01 08:53:58+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (73, 5, 'Белый дом обнародовал информацию о зарплатах в администрации Трампа', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497646074.html', 'Больше всех среди членов администрации получает старший политический советник президента Марк Хаус. Глава Национального экономического совета при Белом доме Гэри Кон зарабатывает меньше всех. Ранее Трамп также опубликовал информацию о своих доходах за 2016 год.', '2017-07-01 08:42:57+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (74, 5, 'Лидер Южной Кореи назвал условия для начала диалога с КНДР', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497643590.html', 'Президент Республики Корея Мун Чжэ Ин во время выступления в Вашингтоне назвал некоторые условия, которые могут помочь начать диалог с северным соседом.', '2017-07-01 03:24:11+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (75, 5, 'Минобороны США на полгода отложило прием трансгендеров в армию', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497644976.html', 'По данным агентства, решение по данному вопросу отложено до 1 января. Запрет трансгендерам на службу в американской армии был снят при администрации экс-президента США Барака Обамы.', '2017-07-01 06:03:14+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (76, 5, 'В Испании задержали предполагаемого боевика ИГ', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fmezhdunarodnaya-panorama%2F4380130', 'Сотрудники Гражданской гвардии Испании задержали в городе Малага на юге страны мужчину, подозреваемого в участии в боевых действиях в Сирии на стороне террористической группировки &quot;Исламское государство&quot; (ИГ, запрещена в РФ).', '2017-07-01 06:22:59+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (77, 5, 'В Белом Доме на Трампа дважды чуть не уронили лампу', 'https://news.yandex.ru/yandsearch?cl4url=inforeactor.ru%2F84367-v-belom-dome-na-trampa-dvazhdy-chut-ne-uronili-lampu', 'В Вашингтоне в официальным визитом находится президент Южной Кореи Мун Чжэ Ин. Во время подготовки к официальным съемкам рукопожатия Дональда Трампа и Мун Чжэ Ина, корейские журналисты дважды едва не перевернули настольную лампу, стоящую на столе рядом с американским президентом.', '2017-07-01 10:22:58+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (78, 5, 'Генпрокурор Украины объявил о новых подозрениях против Януковича', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F613310', 'Департамент специальных расследований генпрокуратуры Украины объявил о новых подозрениях в адрес экс-президента страны Виктора Януковича и ряда бывших высокопоставленных чиновников. Об этом в социальной сети Facebook написал генпрокурор Украины Юрий Луценко, передает «Газета.ру».', '2017-07-01 03:52:47+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (79, 5, 'А. Лукашенко на 4-м форуме регионов Беларуси и РФ напомнил о необходимости решать нефтегазовые вопросы', 'https://news.yandex.ru/yandsearch?cl4url=neftegaz.ru%2Fnews%2Fview%2F162574%2F', 'На состоявшемся 29-30 июня 2017 г в г Москве 4 м Форуме регионов России и Беларуси А. Лукашенко дерзко напомнил о согласованных ранее в г Санкт-Петербурге принципиальных подходах сотрудничества в нефтегазе до 2025 г. Об этом А. Лукашенко поведал 30 июня 2017 г на заседании Высшего государственного совета (ВГС) Союзного государства.', '2017-07-01 11:21:10+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (80, 5, 'Экс-глава Минобороны Сердюков вошел в новый совет директоров ОАК', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F613266', 'Из нового состава совета директоров ОАК выбыли глава Внешэкономбанка Сергей Горьков и гендиректор «Ростеха» Сергей Чемезов. Остальные девять сохранили места. В ОАК входят крупнейшие авиастроительные предприятия России.', '2017-07-01 00:20:08+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (83, 5, 'Новый премьер Сербии заявила о нежелании вводить санкции против России', 'https://news.yandex.ru/yandsearch?cl4url=rg.ru%2F2017%2F06%2F30%2Fnovyj-premer-serbii-zaiavila-o-nezhelanii-vvodit-sankcii-protiv-rossii.html', 'Премьер-министр Сербии Ана Брнабич, которая накануне была избрана председателем правительства страны, заявила, что новый кабинет министров не будет вводить санкции в отношении России.', '2017-06-30 22:25:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (85, 6, 'Число пострадавших от стихии в Москве увеличилось до 16 человек', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fproisshestviya%2F4380221', '&quot;В Москве пострадали 16 человек, шесть из них находятся в больницах с травами различной степени тяжести, среди них один ребенок&quot;, - сказал собеседник агентства. Десятерым пострадавшим оказана медицинская помощь. Еще три человека пострадали от непогоды в Тульской области.', '2017-07-01 10:39:55+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (84, 5, 'Путин и Меркель обсудили темы предстоящего саммита G20', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fpolitika%2F4379720', 'Президент России Владимир Путин и федеральный канцлер ФРГ Ангела Меркель обсудили темы предстоящего саммита &quot;Большой двадцатки&quot; (G20). Об этом сообщила в пятницу пресс-служба Кремля.', '2017-06-30 20:46:28+04', 1);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (82, 5, 'В ФСБ прокомментировали задержание российских пограничников на Украине', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170630%2F1497635362.html', 'Два сотрудника пограничного управления по Крыму в ночь на 30 июня сбились с маршрута и вышли на территорию Украины, где были задержаны, сообщила пресс-служба ФСБ России. В ведомстве пояснили, что на российско-украинской границе проводились учения. Инцидент произошел в районе города Армянск.', '2017-06-30 21:04:00+04', 1);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (87, 6, 'В Токио школьницам запретили ходить на свидания за деньги', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497645820.html', 'В настоящее время в Токио, согласно информации токийской полиции, существует около 110 коммерческих предприятий и около 30 незарегистрированных компаний, которые предлагают услуги по организации свиданий со школьницами. Очень часто на такие свидания направляют девушек младше 18 лет.', '2017-07-01 08:13:40+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (88, 6, 'Лидер Южной Кореи назвал условия для начала диалога с КНДР', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497643590.html', 'Президент Республики Корея Мун Чжэ Ин во время выступления в Вашингтоне назвал некоторые условия, которые могут помочь начать диалог с северным соседом.', '2017-07-01 03:24:11+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (89, 6, 'Белый дом обнародовал информацию о зарплатах в администрации Трампа', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497646074.html', 'Больше всех среди членов администрации получает старший политический советник президента Марк Хаус. Глава Национального экономического совета при Белом доме Гэри Кон зарабатывает меньше всех. Ранее Трамп также опубликовал информацию о своих доходах за 2016 год.', '2017-07-01 08:42:57+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (91, 6, 'В России на 300 рублей вырос минимальный размер оплаты труда', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Feconomy%2F20170701%2F1497641852.html', 'С первого июля минимальный размер оплаты труда (МРОТ) повысился на 300 рублей. Теперь МРОТ составит 7,8 тысяч рублей в месяц. Отныне работодатель не может установить ежемесячную заработную плату ниже этой суммы, если сотрудник отработал норму.', '2017-07-01 04:05:59+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (92, 6, 'Генпрокурор Украины объявил о новых подозрениях против Януковича', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F613310', 'Департамент специальных расследований генпрокуратуры Украины объявил о новых подозрениях в адрес экс-президента страны Виктора Януковича и ряда бывших высокопоставленных чиновников. Об этом в социальной сети Facebook написал генпрокурор Украины Юрий Луценко, передает «Газета.ру».', '2017-07-01 03:52:47+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (93, 6, 'Путин и Меркель обсудили темы предстоящего саммита G20', 'https://news.yandex.ru/yandsearch?cl4url=tass.ru%2Fpolitika%2F4379720', 'Президент России Владимир Путин и федеральный канцлер ФРГ Ангела Меркель обсудили темы предстоящего саммита &quot;Большой двадцатки&quot; (G20). Об этом сообщила в пятницу пресс-служба Кремля.', '2017-06-30 20:46:28+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (94, 6, 'Около 450 рейсов задержали в аэропортах Москвы из-за непогоды', 'https://news.yandex.ru/yandsearch?cl4url=iz.ru%2Fnode%2F613339', 'В аэропортах Москвы задержано уже 450 авиарейсов и более 40 отменены из-за ливня, обрушившегося 30 июня на столичный регион.', '2017-07-01 08:07:39+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (95, 6, 'Лавров и Киссинджер обсудили «ненормальные» отношения России и США', 'https://news.yandex.ru/yandsearch?cl4url=www.rbc.ru%2Fpolitics%2F30%2F06%2F2017%2F59560ec59a794776dc10e7a2', 'Министр иностранных дел России Сергей Лавров на «Примаковских чтениях» совместно с бывшим госсекретарем США Генри Киссинджером обсудили внешнюю политику обеих стран. Глава МИД при этом затронул тему будущей встречи президентов Владимира Путина и Дональда Трампа, сообщает корреспондент РБК.', '2017-06-30 12:52:20+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (96, 6, 'Путин и Лукашенко заглянули в будущее Союзного государства', 'https://news.yandex.ru/yandsearch?cl4url=www.gazeta.ru%2Fbusiness%2F2017%2F06%2F30%2F10756133.shtml', 'Белоруссия будет мировой IT-державой, судьба России решится в битве за роботизацию экономики, а между странами отменят роуминг. Таким увидели будущее Союзного государства президенты Владимир Путин и Александр Лукашенко.', '2017-06-30 23:00:50+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (97, 6, 'Один человек погиб в результате стрельбы в Нью-Йорке', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fworld%2F20170701%2F1497642543.html', 'Один человек погиб, еще несколько ранены при стрельбе в нью-йоркской больнице, нападавший покончил с собой. Об этом сообщил мэр города Билл де Блазио. Как заявил градоначальник, погибший был врачом.', '2017-07-01 02:05:00+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (98, 6, 'Пятничный дождь принес в Москву более 90% месячной нормы осадков', 'https://news.yandex.ru/yandsearch?cl4url=ria.ru%2Fsociety%2F20170701%2F1497648128.html', 'Более 90% от месячной нормы осадков принес в Москву ливень, начавшийся в последний июньский день, сообщили РИА Новости в погодном центре &quot;Фобос&quot;.', '2017-07-01 10:39:49+04', 0);
INSERT INTO news (nid, chid, title, link, description, "pubDate", likes) VALUES (99, 6, 'Россия вошла в пятерку стран с крупнейшей теневой экономикой', 'https://news.yandex.ru/yandsearch?cl4url=www.rbc.ru%2Feconomics%2F30%2F06%2F2017%2F595649079a79470e968e7bff', 'Россия вошла в пятерку крупнейших теневых экономик, заняв четвертое место в рейтинге, куда включены 28 стран.', '2017-06-30 18:28:10+04', 0);


--
-- TOC entry 1800 (class 0 OID 0)
-- Dependencies: 142
-- Name: news_nid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('news_nid_seq', 183, true);


--
-- TOC entry 1785 (class 0 OID 28617)
-- Dependencies: 140
-- Data for Name: rss_channels; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO rss_channels (name, url, link, chid) VALUES ('Яндекс.Новости: Футбол', 'https://news.yandex.ru/football.rss', 'https://news.yandex.ru/football.html', 2);
INSERT INTO rss_channels (name, url, link, chid) VALUES ('Яндекс.Новости: В мире', 'https://news.yandex.ru/world.rss', 'https://news.yandex.ru/world.html', 1);
INSERT INTO rss_channels (name, url, link, chid) VALUES ('Яндекс.Новости: Недвижимость', 'https://news.yandex.ru/realty.rss', 'https://news.yandex.ru/realty.html', 3);
INSERT INTO rss_channels (name, url, link, chid) VALUES ('Яндекс.Новости: Здоровье', 'https://news.yandex.ru/health.rss', 'https://news.yandex.ru/health.html', 4);
INSERT INTO rss_channels (name, url, link, chid) VALUES ('Яндекс.Новости: Политика', 'https://news.yandex.ru/politics.rss', 'https://news.yandex.ru/politics.html', 5);
INSERT INTO rss_channels (name, url, link, chid) VALUES ('Яндекс.Новости: Главные новости', 'https://news.yandex.ru/index.rss', 'https://news.yandex.ru/index.html', 6);


--
-- TOC entry 1801 (class 0 OID 0)
-- Dependencies: 141
-- Name: rss_channels_chid_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('rss_channels_chid_seq', 6, true);


--
-- TOC entry 1698 (class 2606 OID 28700)
-- Name: news_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY news
    ADD CONSTRAINT news_pkey PRIMARY KEY (nid);


--
-- TOC entry 1696 (class 2606 OID 28643)
-- Name: rss_channels_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres; Tablespace: 
--

ALTER TABLE ONLY rss_channels
    ADD CONSTRAINT rss_channels_pkey PRIMARY KEY (chid);


--
-- TOC entry 1795 (class 0 OID 0)
-- Dependencies: 3
-- Name: public; Type: ACL; Schema: -; Owner: postgres
--

REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM postgres;
GRANT ALL ON SCHEMA public TO postgres;
GRANT ALL ON SCHEMA public TO PUBLIC;


-- Completed on 2017-07-01 18:15:58

--
-- PostgreSQL database dump complete
--

